[master]
# Replace with your Jenkins/master node host details.
# Example:
# master.example.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[workers]
# Replace with your worker node host details.
# Example:
# worker.example.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[app_servers:children]
workers
